name: publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
     uses: actions/checkout@v2
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm run test

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

    